[package]
name = "photos-web-server-derive"
version = "0.1.0"
authors = ["Graham Rushton <graham.rushton@argondesign.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.8"
syn = "1.0.58"
