version: '3.7'
services:
  devbox:
    build:
      context: .
      args:
        USER: ${USER:?USER environment variable must be set}
        UID: ${UID:?UID environment variable must be set}
        DOCKER_GID: ${DOCKER_GID:?DOCKER_GID environment variable must be set} 
    volumes:
      - ${WORKSPACE:?WORKSPACE environment variable must be set}:/home/${USER}/workspace
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: photos-devbox
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    ports:
      - "8080:8080"
